spring:
  application:
    name: homie-backend
  datasource:
    url: jdbc:h2:mem:homiedb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
